"""Add VIP and Asaas fields to User

Revision ID: 5cc56dc26eb6
Revises: cc7f8dc7e0a4
Create Date: 2026-08-08 08:40:28.123893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cc56dc26eb6'
down_revision: Union[str, Sequence[str], None] = 'cc7f8dc7e0a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_vip', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('asaas_customer_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'asaas_customer_id')
    op.drop_column('users', 'is_vip')
    # ### end Alembic commands ###
