"""Add IG columns to BrandProfile

Revision ID: cc7f8dc7e0a4
Revises: 4fdda1a71236
Create Date: 2026-08-08 08:32:32.355406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc7f8dc7e0a4'
down_revision: Union[str, Sequence[str], None] = '4fdda1a71236'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand_profiles', sa.Column('ig_access_token', sa.String(), nullable=True))
    op.add_column('brand_profiles', sa.Column('ig_account_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brand_profiles', 'ig_account_id')
    op.drop_column('brand_profiles', 'ig_access_token')
    # ### end Alembic commands ###
